### PR TITLE
Separate CRDs from helm template so in order to skip CRD deployment

### PR DESCRIPTION
**Pull request by cedricmckinnie**
I'm unable to separate CRDs from other resources deployed via helm

### CODE REVIEW

**Comment by cedricmckinnie** [comment]
@raffaelespazzoli Hey I'm not 100% sure this will fix the problem. I'm running into some issues with running the Makefile as I run on Apple Silicon (M1). Does this deploy a test helm package that I can pull to verify if this separated the CRDs correctly?

**Comment by raffaelespazzoli** [comment]
There should be a parameter in help to not install the CRD if that is what you want to achieve. @sabre1041

**Comment by raffaelespazzoli** [comment]
@davgordo any idea why this might have been commented out? What do we do for the other operators? overall this seems a good idea.

**Comment by raffaelespazzoli** [comment]
I figured out what happened, we should have this.

**Pull request merged**
