### PR TITLE
Add ability to customize keepalived-template.yaml via ConfigMap

### PR DESCRIPTION
**Pull request by cedricmckinnie**
This should provide end users of this operator to customize keepalived-template.yaml by adding a ConfigMap and pointing to it via helm chart. It could be helpful for hard-coding configurations or being able to test changes on the fly when working with the operator without having to rebuild/push or develop locally for some use cases.

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
it looks good to me.

**Comment by raffaelespazzoli** [comment]
update on both PR, they look good, but the build system is broken. We have not kept it up to date. I'm trying to get help with it.

**Comment by cedricmckinnie** [comment]
I actually realized that I need to copy the whole keepalived-template.yaml to a ConfigMap in order for the operator to be able to generate the other resources there. Will circle back with the update soon.

**Comment by cedricmckinnie** [comment]
As for the build system, I encountered that error when trying to run it locally. Seems to have a hard dependency on go1.17. Try bumping and running a copy of the pipeline on another branch.

**Comment by raffaelespazzoli** [comment]
@cedricmckinnie can you rebase, there is a conflict after we made all the changes to update the build system

**Pull request closed without merging**
